export const Types = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOAD_USER: 'LOAD_USER',
    SET_ERROR: 'SET_ERROR',


    GET_CHARACTERS: 'GET_CHARACTERS',
    GET_CHARACTERS_LOADING: 'GET_CHARACTERS_LOADING',
    GET_CHARACTERS_ERROR: 'GET_CHARACTERS_ERROR',

    FILTER_CHARACTERS: 'FILTER_CHARACTERS',

  }